### ISSUE TITLE
[META] TSLint Compatibility

### ISSUE THREAD

**Issue by dannyfritz** [bradzacher/eslint-plugin-typescript#5]
- [x] [array-type](https://palantir.github.io/tslint/rules/array-type/) (#211 )
- [x] [adjacent-overload-signatures](http://palantir.github.io/tslint/rules/adjacent-overload-signatures/) (#37 )
- [x] [ban-types](https://palantir.github.io/tslint/rules/ban-types/) (#181 )
- [ ] [callable-types](https://palantir.github.io/tslint/rules/callable-types/)
- [x] [class-name](https://palantir.github.io/tslint/rules/class-name/) (#44 `class-name-casing`)
- [x] [interface-name](http://palantir.github.io/tslint/rules/interface-name/) (#10 `interface-name-prefix`)
- [x] [interface-over-type-literal](https://palantir.github.io/tslint/rules/interface-over-type-literal/) (#15 `no-type-literal`)
- [x] [member-access](http://palantir.github.io/tslint/rules/member-access/) (#4 `explicit-member-accessibility`)
- [x] [member-ordering](http://palantir.github.io/tslint/rules/member-ordering/) (#23 )
- [x] [no-angle-bracket-type-assertion](http://palantir.github.io/tslint/rules/no-angle-bracket-type-assertion/) (#13 )
- [x] [no-any](http://palantir.github.io/tslint/rules/no-any/) (#8 `no-explicit-any`)
- [x] [no-empty-interface](https://palantir.github.io/tslint/rules/no-empty-interface/) (#39 )
- [ ] [no-inferred-empty-object-type](https://palantir.github.io/tslint/rules/no-inferred-empty-object-type/)
- [x] [no-inferrable-types](http://palantir.github.io/tslint/rules/no-inferrable-types/) (#124 )
- [x] [no-internal-module](http://palantir.github.io/tslint/rules/no-internal-module/) (#22 `prefer-namespace-keyword`)
- [ ] [no-mergeable-namespace](http://palantir.github.io/tslint/rules/no-mergeable-namespace/)
- [ ] [no-misused-new](https://palantir.github.io/tslint/rules/no-misused-new/)
- [x] [no-namespace](http://palantir.github.io/tslint/rules/no-namespace/) (#21 )
- [x] [no-non-null-assertion](https://palantir.github.io/tslint/rules/no-non-null-assertion/) (#108 )
- [ ] [no-object-literal-type-assertion](https://palantir.github.io/tslint/rules/no-object-literal-type-assertion/)
- [x] [no-parameter-properties](http://palantir.github.io/tslint/rules/no-parameter-properties/) (#53 )
- [x] [no-reference](http://palantir.github.io/tslint/rules/no-reference/) (#6 `no-triple-slash-reference`)
- [ ] [no-reference-input](http://palantir.github.io/tslint/rules/no-reference-input/)
- [ ] [no-redundant-jsdoc](https://palantir.github.io/tslint/rules/no-redundant-jsdoc/)
- [ ] [no-unsafe-any](https://palantir.github.io/tslint/rules/no-unsafe-any/)
- [ ] [no-unnecessary-type-assertion](https://palantir.github.io/tslint/rules/no-unnecessary-type-assertion/)
- [x] [no-var-requires](https://palantir.github.io/tslint/rules/no-var-requires/) (#114 )
- [x] [type-literal-delimiter](https://palantir.github.io/tslint/rules/type-literal-delimiter/) (#48 `member-delimiter-style`)
- [ ] [typedef](http://palantir.github.io/tslint/rules/typedef/)
- [x] [typedef-whitespace](http://palantir.github.io/tslint/rules/typedef-whitespace/) (`type-annotation-spacing`)
- [ ] [unifed-signatures](https://palantir.github.io/tslint/rules/unified-signatures/)

**Comment by dannyfritz** [comment]
@weirdpattern Any of the unchecked items are up for grabs :smile: . My work got unexpectedly busy and I won't be active on this for a little while.

**Comment by weirdpattern** [comment]
@dannyfritz alright, I will start working on some of these... still deciding which ones though... 
I will let you know, thanks!

**Comment by weirdpattern** [comment]
I'm working on no-parameter-properties and no-internal-modules...

**Comment by dannyfritz** [comment]
Huge shoutout to @weirdpattern for taking us over the 50% line! 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by weirdpattern** [comment]
Update

no-parameter-properties is currently blocked due to TypeScript Parser [bug 143](https://github.com/eslint/typescript-eslint-parser/issues/143). I have a solution, but I'm waiting on @nzakas to confirm how the wants to proceed.

no-inferrable-types is currently blocked due to TypeScript Parser [bug 146](https://github.com/eslint/typescript-eslint-parser/issues/146). PR is being reviewed.

So, working on member-ordering for now =]

**Comment by dannyfritz** [comment]
@weirdpattern can you add the compatibility section into #23?

**Comment by weirdpattern** [comment]
of course, not in front of my computer at the moment, but will do it tonight...

**Comment by weirdpattern** [comment]
@dannyfritz done!

**Comment by weirdpattern** [comment]
Hi @dannyfritz can you mark member-ordering as completed?
It was merged this afternoon... Thanks!

**Comment by dannyfritz** [comment]
Thanks for you work!

**Comment by j-f1** [comment]
How about [`class-name`](https://palantir.github.io/tslint/rules/class-name) ([TSLint rule source](https://github.com/palantir/tslint/blob/6b6f43ad17bfe186fea300eb327a2e0838f36e51/src/rules/classNameRule.ts))?

**Comment by weirdpattern** [comment]
All, I'm going to start working on no-parameter-properties.

**Comment by weirdpattern** [comment]
Now working on no-mergeable-namespace and no-non-null-assertion...

**Comment by corbinu** [comment]
@weirdpattern sweet thanks so much for all the work your doing!

**Comment by weirdpattern** [comment]
I was reviewing the remaining rules, I believe #48 is a superset of [type-literal-delimiter](https://palantir.github.io/tslint/rules/type-literal-delimiter/)... I mean it does something similar, and includes interfaces too... thoughts?

**Comment by dannyfritz** [comment]
Yes, I do agree the functionality is met with `member-delimiter-style`. Thanks!

**Comment by dannyfritz** [comment]
It is worth someone else going through the TSLint rules and seeing if you agree I grabbed all the relevant TS specific ones. https://palantir.github.io/tslint/rules/

**Comment by j-f1** [comment]
From the list above:

TypeScript-specific
- [ ] [ban-types]
- [ ] [no-misused-new]
- [ ] [no-object-literal-type-assertion]

Maintainability
- [ ] [no-mergeable-namespace]

Style
- [ ] [array-type]
- [ ] [callable-types]
- [ ] [interface-over-type-literal]
- [ ] [no-parameter-properties]
- [ ] [no-reference-import]

[ban-types]: https://palantir.github.io/tslint/rules/ban-types
[no-misused-new]: https://palantir.github.io/tslint/rules/no-misused-new
[no-object-literal-type-assertion]: https://palantir.github.io/tslint/rules/no-object-literal-type-assertion

[no-mergeable-namespace]: https://palantir.github.io/tslint/rules/no-mergeable-namespace

[array-type]: https://palantir.github.io/tslint/rules/array-type
[callable-types]: https://palantir.github.io/tslint/rules/callable-types
[interface-over-type-literal]: https://palantir.github.io/tslint/rules/interface-over-type-literal
[no-parameter-properties]: https://palantir.github.io/tslint/rules/no-parameter-properties
[no-reference-import]: https://palantir.github.io/tslint/rules/no-reference-import

<details><summary>Markdown Source</summary>

```markdown
TypeScript-specific
- [ ] [ban-types]
- [ ] [no-misused-new]
- [ ] [no-object-literal-type-assertion]

Maintainability
- [ ] [no-mergeable-namespace]

Style
- [ ] [array-type]
- [ ] [callable-types]
- [ ] [interface-over-type-literal]
- [ ] [no-parameter-properties]
- [ ] [no-reference-import]

[ban-types]: https://palantir.github.io/tslint/rules/ban-types
[no-misused-new]: https://palantir.github.io/tslint/rules/no-misused-new
[no-object-literal-type-assertion]: https://palantir.github.io/tslint/rules/no-object-literal-type-assertion

[no-mergeable-namespace]: https://palantir.github.io/tslint/rules/no-mergeable-namespace

[array-type]: https://palantir.github.io/tslint/rules/array-type
[callable-types]: https://palantir.github.io/tslint/rules/callable-types
[interface-over-type-literal]: https://palantir.github.io/tslint/rules/interface-over-type-literal
[no-parameter-properties]: https://palantir.github.io/tslint/rules/no-parameter-properties
[no-reference-import]: https://palantir.github.io/tslint/rules/no-reference-import
```
</details><br><br>

Rules requiring type info:

TypeScript-specific
- [ ] [no-unnecessary-type-assertion]
- [ ] [promise-function-async]

Functionality
- [ ] [await-promise]
- [ ] [no-floating-promises]
- [ ] [no-for-in-array]
- [ ] [no-inferred-empty-object-type]
- [ ] [no-unbound-method]
- [ ] [no-unsafe-any]
- [ ] [no-unused-variable]
- [ ] [no-void-expression]
- [ ] [restrict-plus-operands]
- [ ] [strict-boolean-expressions]
- [ ] [strict-type-predicates]
- [ ] [use-default-type-parameter] (i.e. `type Foo<T=Bar> = ...; const var: Foo<Bar> = ...;`

Maintainability
- [ ] [deprecation]

Style
- [ ] [no-unnecessary-qualifier]
- [ ] [return-undefined]

[no-unnecessary-type-assertion]: https://palantir.github.io/tslint/rules/no-unnecessary-type-assertion
[promise-function-async]: https://palantir.github.io/tslint/rules/promise-function-async

[await-promise]: https://palantir.github.io/tslint/rules/await-promise
[no-floating-promises]: https://palantir.github.io/tslint/rules/no-floating-promises
[no-for-in-array]: https://palantir.github.io/tslint/rules/no-for-in-array
[no-inferred-empty-object-type]: https://palantir.github.io/tslint/rules/no-inferred-empty-object-type
[no-unbound-method]: https://palantir.github.io/tslint/rules/no-unbound-method
[no-unsafe-any]: https://palantir.github.io/tslint/rules/no-unsafe-any
[no-unused-variable]: https://palantir.github.io/tslint/rules/no-unused-variable
[no-void-expression]: https://palantir.github.io/tslint/rules/no-void-expression
[restrict-plus-operands]: https://palantir.github.io/tslint/rules/restrict-plus-operands
[strict-boolean-expressions]: https://palantir.github.io/tslint/rules/strict-boolean-expressions
[strict-type-predicates]: https://palantir.github.io/tslint/rules/strict-type-predicates
[use-default-type-parameter]: https://palantir.github.io/tslint/rules/use-default-type-parameter

[deprecation]: https://palantir.github.io/tslint/rules/deprecation

[no-unnecessary-qualifier]: https://palantir.github.io/tslint/rules/no-unnecessary-qualifier
[return-undefined]: https://palantir.github.io/tslint/rules/return-undefined

<details><summary>Markdown source</summary>

```markdown
TypeScript-specific
- [ ] [no-unnecessary-type-assertion]
- [ ] [promise-function-async]

Functionality
- [ ] [await-promise]
- [ ] [no-floating-promises]
- [ ] [no-for-in-array]
- [ ] [no-inferred-empty-object-type]
- [ ] [no-unbound-method]
- [ ] [no-unsafe-any]
- [ ] [no-unused-variable]
- [ ] [no-void-expression]
- [ ] [restrict-plus-operands]
- [ ] [strict-boolean-expressions]
- [ ] [strict-type-predicates]
- [ ] [use-default-type-parameter] (i.e. `type Foo<T=Bar> = ...; const var: Foo<Bar> = ...;`

Maintainability
- [ ] [deprecation]

Style
- [ ] [no-unnecessary-qualifier]
- [ ] [return-undefined]

[no-unnecessary-type-assertion]: https://palantir.github.io/tslint/rules/no-unnecessary-type-assertion
[promise-function-async]: https://palantir.github.io/tslint/rules/promise-function-async

[await-promise]: https://palantir.github.io/tslint/rules/await-promise
[no-floating-promises]: https://palantir.github.io/tslint/rules/no-floating-promises
[no-for-in-array]: https://palantir.github.io/tslint/rules/no-for-in-array
[no-inferred-empty-object-type]: https://palantir.github.io/tslint/rules/no-inferred-empty-object-type
[no-unbound-method]: https://palantir.github.io/tslint/rules/no-unbound-method
[no-unsafe-any]: https://palantir.github.io/tslint/rules/no-unsafe-any
[no-unused-variable]: https://palantir.github.io/tslint/rules/no-unused-variable
[no-void-expression]: https://palantir.github.io/tslint/rules/no-void-expression
[restrict-plus-operands]: https://palantir.github.io/tslint/rules/restrict-plus-operands
[strict-boolean-expressions]: https://palantir.github.io/tslint/rules/strict-boolean-expressions
[strict-type-predicates]: https://palantir.github.io/tslint/rules/strict-type-predicates
[use-default-type-parameter]: https://palantir.github.io/tslint/rules/use-default-type-parameter

[deprecation]: https://palantir.github.io/tslint/rules/deprecation

[no-unnecessary-qualifier]: https://palantir.github.io/tslint/rules/no-unnecessary-qualifier
[return-undefined]: https://palantir.github.io/tslint/rules/return-undefined
```
</details><br><br>


non-TS-only:
“TypeScript-specific”
- [ ] [no-import-side-effect] — I think this might be better in `eslint-plugin-import`
- [ ] [only-arrow-functions]
- [ ] [prefer-for-of]

Maintainabliltiy
- [ ] [no-default-export]

Style
- [ ] [jsdoc-format]
- [ ] [match-default-export-name]
- [ ] [no-boolean-literal-compare] (I think we can do it without type info)


[no-import-side-effect]: https://palantir.github.io/tslint/rules/no-import-side-effect
[only-arrow-functions]: https://palantir.github.io/tslint/rules/only-arrow-functions
[prefer-for-of]: https://palantir.github.io/tslint/rules/prefer-for-of
[no-default-export]: https://palantir.github.io/tslint/rules/no-default-export
[jsdoc-format]: https://palantir.github.io/tslint/rules/jsdoc-format
[match-default-export-name]: https://palantir.github.io/tslint/rules/match-default-export-name
[no-boolean-literal-compare]: https://palantir.github.io/tslint/rules/no-boolean-literal-compare

<details><summary>Markdown source</summary>

```markdown
- [ ] [no-import-side-effect] — I think this might be better in `eslint-plugin-import`
- [ ] [only-arrow-functions]
- [ ] [prefer-for-of]

Maintainabliltiy
- [ ] [no-default-export]

Style
- [ ] [jsdoc-format]
- [ ] [match-default-export-name]
- [ ] [no-boolean-literal-compare] (I think we can do it without type info)


[no-import-side-effect]: https://palantir.github.io/tslint/rules/no-import-side-effect
[only-arrow-functions]: https://palantir.github.io/tslint/rules/only-arrow-functions
[prefer-for-of]: https://palantir.github.io/tslint/rules/prefer-for-of
[no-default-export]: https://palantir.github.io/tslint/rules/no-default-export
[jsdoc-format]: https://palantir.github.io/tslint/rules/jsdoc-format
[match-default-export-name]: https://palantir.github.io/tslint/rules/match-default-export-name
[no-boolean-literal-compare]: https://palantir.github.io/tslint/rules/no-boolean-literal-compare
```
</details>

**Comment by weirdpattern** [comment]
Hey @j-f1, this is great! One question though, some of these are common to both JavaScript (es5, es6, etc) and TypeScript, so not sure if they should be defined here or at the eslint level... I know eslint already offers some rules to validate jsdoc and to restrict syntax like for-in...

**Comment by j-f1** [comment]
The difference between ESLint’s `valid-jsdoc` and TSLint’s `jsdoc-format` is that TSLint just validates the syntax; whereas ESLint requires defining parameter and return type info.

**Comment by dannyfritz** [comment]
It might be worth adding those to this list and opening a pr in eslint to close it?

**Comment by dannyfritz** [comment]
I think the line that should be drawn for including in this repo is: can this rule be used without typescript?

**Comment by macklinu** [comment]
`no-non-null-assertion` can be checked in the original list now that #108 has been merged.

**Comment by nevir** [comment]
`no-floating-promises` would be a huge win, and seems like it would require TypeScript's knowledge of an expression's return type

**Comment by armano2** [comment]
@bradzacher i'm going to work on `promise-function-async`

**Comment by dannyfritz** [comment]
TSLint has changed since I originally made this issue a few times. If someone wants to do the research to corroborate where we are with the moving target I'd gladly update the original list.

**Comment by weirdpattern** [comment]
Just a thought...

Would it be better to move all these pending rules to the README.md or maybe ROADMAP.md file? 

I think it will give users a clear idea of where we are heading without having to search this info in a bug?

**Comment by armano2** [comment]
i'm going to work now on `no-misused-new`

**Comment by armano2** [comment]
- [ ] [type-literal-delimiter]
- [ ] [no-reference-import]
- [ ] [no-redundant-jsdoc]
- [x] [no-parameter-properties]
- [x] [no-angle-bracket-type-assertion]
- [x] [interface-over-type-literal]
- [x] [interface-name]
- [ ] [callable-types]
- [ ] [array-type]
- [ ] [no-mergeable-namespace]
- [ ] [no-object-literal-type-assertion]
- [ ] [no-misused-new]
- [ ] [unified-signatures]
- [ ] [typedef-whitespace]
- [ ] [typedef]
- [ ] [no-var-requires]
- [ ] [no-non-null-assertion]
- [ ] [no-namespace]
- [ ] [no-internal-module]
- [ ] [no-inferrable-types]
- [ ] [no-empty-interface]
- [ ] [no-any]
- [ ] [member-access]
- [ ] [ban-types]
- [ ] [adjacent-overload-signatures]

### With Type Info
- [ ] [no-unnecessary-type-assertion]
- [ ] [await-promise]
- [ ] [no-floating-promises]
- [ ] [no-inferred-empty-object-type]
- [ ] [no-unbound-method]
- [ ] [no-unsafe-any]
- [ ] [no-unused-variable]
- [ ] [strict-boolean-expressions]
- [ ] [strict-type-predicates]
- [ ] [use-default-type-parameter]
- [ ] [prefer-readonly]
- [ ] [match-default-export-name]
- [ ] [no-boolean-literal-compare]
- [ ] [no-unnecessary-qualifier]

[type-literal-delimiter]: https://palantir.github.io/tslint/rules/type-literal-delimiter/
[no-reference-import]: https://palantir.github.io/tslint/rules/no-reference-import/
[no-redundant-jsdoc]: https://palantir.github.io/tslint/rules/no-redundant-jsdoc/
[no-parameter-properties]: https://palantir.github.io/tslint/rules/no-parameter-properties/
[no-angle-bracket-type-assertion]: https://palantir.github.io/tslint/rules/no-angle-bracket-type-assertion/
[interface-over-type-literal]: https://palantir.github.io/tslint/rules/interface-over-type-literal/
[interface-name]: https://palantir.github.io/tslint/rules/interface-name/
[callable-types]: https://palantir.github.io/tslint/rules/callable-types/
[array-type]: https://palantir.github.io/tslint/rules/array-type/
[no-mergeable-namespace]: https://palantir.github.io/tslint/rules/no-mergeable-namespace/
[no-object-literal-type-assertion]: https://palantir.github.io/tslint/rules/no-object-literal-type-assertion/
[no-misused-new]: https://palantir.github.io/tslint/rules/no-misused-new/
[unified-signatures]: https://palantir.github.io/tslint/rules/unified-signatures/
[typedef-whitespace]: https://palantir.github.io/tslint/rules/typedef-whitespace/
[typedef]: https://palantir.github.io/tslint/rules/typedef/
[no-var-requires]: https://palantir.github.io/tslint/rules/no-var-requires/
[no-non-null-assertion]: https://palantir.github.io/tslint/rules/no-non-null-assertion/
[no-namespace]: https://palantir.github.io/tslint/rules/no-namespace/
[no-internal-module]: https://palantir.github.io/tslint/rules/no-internal-module/
[no-inferrable-types]: https://palantir.github.io/tslint/rules/no-inferrable-types/
[no-empty-interface]: https://palantir.github.io/tslint/rules/no-empty-interface/
[no-any]: https://palantir.github.io/tslint/rules/no-any/
[member-access]: https://palantir.github.io/tslint/rules/member-access/
[ban-types]: https://palantir.github.io/tslint/rules/ban-types/
[adjacent-overload-signatures]: https://palantir.github.io/tslint/rules/adjacent-overload-signatures/
[no-unnecessary-type-assertion]: https://palantir.github.io/tslint/rules/no-unnecessary-type-assertion/
[await-promise]: https://palantir.github.io/tslint/rules/await-promise/
[no-floating-promises]: https://palantir.github.io/tslint/rules/no-floating-promises/
[no-inferred-empty-object-type]: https://palantir.github.io/tslint/rules/no-inferred-empty-object-type/
[no-unbound-method]: https://palantir.github.io/tslint/rules/no-unbound-method/
[no-unsafe-any]: https://palantir.github.io/tslint/rules/no-unsafe-any/
[no-unused-variable]: https://palantir.github.io/tslint/rules/no-unused-variable/
[strict-boolean-expressions]: https://palantir.github.io/tslint/rules/strict-boolean-expressions/
[strict-type-predicates]: https://palantir.github.io/tslint/rules/strict-type-predicates/
[use-default-type-parameter]: https://palantir.github.io/tslint/rules/use-default-type-parameter/
[prefer-readonly]: https://palantir.github.io/tslint/rules/prefer-readonly/
[match-default-export-name]: https://palantir.github.io/tslint/rules/match-default-export-name/
[no-boolean-literal-compare]: https://palantir.github.io/tslint/rules/no-boolean-literal-compare/
[no-unnecessary-qualifier]: https://palantir.github.io/tslint/rules/no-unnecessary-qualifier/

**Comment by j-f1** [comment]
See #228

**Comment by bradzacher** [comment]
Thanks to @j-f1, we can now track this via https://github.com/bradzacher/eslint-plugin-typescript/blob/master/ROADMAP.md

Unless anyone has any objections, I'll close this issue.

**Comment by dannyfritz** [comment]
No objection from me
